version: '3'
services:
  ruby:
    container_name: ruby
    build: .
    command: bundle exec rackup -o 0.0.0.0
    ports:
    - 9292:9292
    volumes:
      - .:/app:rw
    tty: true
    stdin_open: true
    env_file: .env
    depends_on:
      - db
  db:
    container_name: db2
    image: postgres:10-alpine
    ports:
    - 5439:5432
    volumes:
      - data-postgres:/var/lib/postgresql/data
volumes:
  data-postgres:
    driver: local
